---
title: "Get Involved"
---

# **Volunteer with Tree-Planting & Stewardship Programs**

-   **MillionTreesNYC** (NYC Parks + NYRP)\
    [Volunteer to plant & care for trees in underserved neighborhoods](https://www.milliontreesnyc.org/)

-   **Trees New York**\
    [Free Citizen Pruner Certification courses to legally care for street trees.](https://www.treesny.org/)

-   **Bronx River Alliance**\
    [Helps restore green spaces along the Bronx River.](https://bronxriver.org/)

# **Advocate for Tree Equity Policies**

-   **Join NYC’s Community Boards:** Push for more tree planting in low-canopy areas

    -   Find your board: [Here](https://www.nyc.gov/site/cau/community-boards.page)

-   **Support (or Demand) City Initiatives**

    -   Advocate for more funding for street trees in low-income areas.

# **Report & Protect Existing Trees**

-   **Use 311 to Request a Street Tree**
    -   Dial **311** or go online at [**NYC 311**](https://portal.311.nyc.gov/) to request a free tree planting in front of your home.

## ***Every tree planted is a step toward climate justice.***
